# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-13 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=120)),
                ('localidad', models.CharField(max_length=35)),
                ('coordenadas', models.CharField(max_length=40)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georef.Programa')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=75)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georef.Programa')),
            ],
        ),
        migrations.AddField(
            model_name='tienda',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georef.Vendedor'),
        ),
    ]
