# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AddField(
            model_name='tienda',
            name='latitud',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='tienda',
            name='longitud',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
