# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef', '0002_auto_20171113_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='programa',
            name='latitud',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='programa',
            name='longitud',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
