# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef', '0003_auto_20171114_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikeys',
            name='id',
        ),
        migrations.AlterField(
            model_name='apikeys',
            name='clave',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
