# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef', '0004_auto_20171114_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='compra_blanqueador',
            field=models.CharField(default='NO COMPRA', max_length=20),
        ),
        migrations.AddField(
            model_name='tienda',
            name='compra_limpido',
            field=models.CharField(default='NO COMPRA', max_length=20),
        ),
        migrations.AddField(
            model_name='tienda',
            name='compra_mensual',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tienda',
            name='compra_otc',
            field=models.CharField(default='NO', max_length=20),
        ),
        migrations.AddField(
            model_name='tienda',
            name='compra_reciente',
            field=models.CharField(default='NO', max_length=20),
        ),
    ]
