# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georef', '0005_auto_20171115_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='compra_limpido',
            new_name='compra_aditivo',
        ),
    ]
