# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georef', '0006_auto_20171115_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='color',
            field=models.CharField(default='Black', max_length=20),
        ),
    ]
